// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/alexrocco/go-orm/internal"
	"github.com/alexrocco/go-orm/internal/handlers"
	"github.com/alexrocco/go-orm/internal/repositories"
	"github.com/alexrocco/go-orm/internal/services"
)

// Injectors from wire.go:

func InitializeApp() app.App {
	db := repositories.NewDB()
	peopleRepo := repositories.NewPeopleRepo(db)
	peopleService := services.NewPeopleService(peopleRepo)
	peopleHandler := handlers.NewPeopleHandler(peopleService)
	appApp := app.NewApp(peopleHandler)
	return appApp
}
